export const PROFESSIONAL_LOGIN_USER = "PROFESSIONAL_LOGIN_USER";
export const PROFESSIONAL_LOGIN_SUCCESS = "PROFESSIONAL_LOGIN_SUCCESS";
export const PROFESSIONAL_LOGOUT_USER = "PROFESSIONAL_LOGOUT_USER";
export const PROFESSIONAL_LOGOUT_USER_SUCCESS = "PROFESSIONAL_LOGOUT_USER_SUCCESS";
export const PROFESSIONAL_API_ERROR = "PROFESSIONAL_API_ERROR";
export const PROFESSIONAL_SOCIAL_LOGIN = "PROFESSIONAL_SOCIAL_LOGIN";
