export const BASIC_LOGIN_USER = "BASIC_LOGIN_USER";
export const BASIC_LOGIN_SUCCESS = "BASIC_LOGIN_SUCCESS";
export const BASIC_LOGOUT_USER = "BASIC_LOGOUT_USER";
export const BASIC_LOGOUT_USER_SUCCESS = "BASIC_LOGOUT_USER_SUCCESS";
export const BASIC_API_ERROR = "BASIC_API_ERROR";
export const BASIC_SOCIAL_LOGIN = "BASIC_SOCIAL_LOGIN";
